version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "LOG[%(levelname)-5s] | %(name)-30s | %(message)s"
  extended:
    format: "%(asctime)s | LOG[%(levelname)-5s] | %(name)-30s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: extended
    filename: output_log.log
    maxBytes: 10485760 # 10MB
    backupCount: 2

loggers:
  root:
    level: INFO
    handlers: [console, file_handler]
    propogate: False
